name: "premake-manager"
description: "Install premake-manager in GitHub Actions"
author: "lolrobbe2"
branding:
  icon: 'package'
  color: 'blue'

inputs:
  tag:
    description: "Release tag of premake5"
    required: true
    default: "v5.0.0-beta7"
runs:
  using: "composite"
  steps:
    - name: install premake5
      shell: bash
      run: premake-manager-cli version install ${{ input.tag}}